#!/bin/bash

set -e

# Debug/Release
CMAKE_GEN_FLAGS="-DCMAKE_CXX_COMPILER=clang++ -DCMAKE_CXX_STANDARD=20 -DCMAKE_BUILD_TYPE=Release"
CMAKE_BUILD_FLAGS=""

format ()
{
    echo "================== FORMATTING =================="
    clang-format -i $(find src/ -name "*.cc" -or -name "*.h")
}

build ()
{
    echo "================== BUILDING =================="
    cmake $CMAKE_GEN_FLAGS -S . -B out
    cmake $CMAKE_BUILD_FLAGS --build out
}

test ()
{
    echo "================== TESTING =================="
    out/test $@
}

_valgrind ()
{
    echo "================== VALGRIND =================="
    # TODO: need to build without asan...
    valgrind -s --leak-check=full --error-exitcode=2 out/katsu $@
}

katsu ()
{
    echo "================== RUNNING =================="
    out/katsu $@
}

if [ $# -eq 0 ]; then
    build
    test
    _valgrind
    katsu
    exit 0
fi

case "$1" in
    f|format)       shift; format ;;
    b|build)        shift; build ;;
    t|test)         shift; build; test $@ ;;
    v|valgrind)     shift; build; _valgrind $@ ;;
    k|katsu|r|run)  shift; build; katsu $@ ;;
    "")                    build; katsu ;;
    *)
        echo "not sure what to do with '$1'" >&2
        exit 1 ;;
esac