#!/bin/bash

if [ $# -ne 1 ]; then
    echo "usage: ./update-test <name>   -- runs test/<test>.katsu in order to generate test/<name>.stdout and test/<name>.stderr" >&2
    echo "       ./update-test -a|--all -- updates all tests under test/" >&2
    exit 1
fi

./run b

update_test ()
{
    name="$1"

    echo "============ RUNNING test/$name.katsu ==============="

    if [ ! -f "test/$name.katsu" ]; then
        echo "test/$name.katsu does not exist" >&2
        echo "some options are:" >&2
        for f in $(find test -name "*.katsu"); do
            echo "  $(basename $f .katsu)" >&2
        done
        exit 1
    fi

    out/katsu test test/$name.katsu > >(tee test/$name.stdout) 2> >(tee test/$name.stderr)

    if [ ! -s "test/$name.stderr" ]; then
        rm -f test/$name.stderr
    fi
}

case "$1" in
    -a|--all)
        for f in $(find test -name "*.katsu"); do
            update_test $(basename $f .katsu)
        done
        ;;
    *)
        update_test "$1"
        ;;
esac
